# 동 단위로 묶기

In [29]:
import pandas as pd
import re
subway_data = pd.read_csv('./subway_info_sigudong.csv', encoding= 'CP949', index_col= 0, header= 0, engine= 'python')
bus_data = pd.read_csv('./bus_info_sigudong.csv', encoding= 'CP949', index_col= 0, header= 0, engine= 'python')


areas = []

## 추가 함수
def add_data(csv_data, results):
    for idx,data in enumerate(subway_data['시구동']):
        if pd.isna(data) == False and data !=  '':
            str_data = re.sub('\d+동', '동', data)

            n_24 = csv_data['24시~1시'][idx]
            n_1 = csv_data['1시~2시'][idx]
            n_2 = csv_data['2시~3시'][idx]
            n_3 = csv_data['3시~4시'][idx]
            n_4 = csv_data['4시~5시'][idx]
            n_5 = csv_data['5시~6시'][idx]
            n_6 = csv_data['6시~7시'][idx]
            n_7 = csv_data['7시~8시'][idx]
            n_8 = csv_data['8시~9시'][idx]
            n_9 = csv_data['9시~10시'][idx]
            n_10 = csv_data['10시~11시'][idx]
            n_11 = csv_data['11시~12시'][idx]
            n_12 = csv_data['12시~13시'][idx]
            n_13 = csv_data['13시~14시'][idx]
            n_14 = csv_data['14시~15시'][idx]
            n_15 = csv_data['15시~16시'][idx]
            n_16 = csv_data['16시~17시'][idx]
            n_17 = csv_data['17시~18시'][idx]
            n_18 = csv_data['18시~19시'][idx]
            n_19 = csv_data['19시~20시'][idx]
            n_20 = csv_data['20시~21시'][idx]
            n_21 = csv_data['21시~22시'][idx]
            n_22 = csv_data['22시~23시'][idx]
            n_23 = csv_data['23시~24시'][idx]

            total = n_1 + n_2 + n_3 + n_4 + n_5 + n_6 + n_7 + n_8 + n_9 + n_10 + n_11 + n_12 + n_13 \
                    + n_14 + n_15 + n_16 + n_17 + n_18 + n_19 + n_20 + n_21 + n_22 + n_23 + n_24

            if str_data not in areas:
                areas.append(str_data)
                results.append(
                    {'area_name': str_data, 'n_24': n_24, 'n_1': n_1, 'n_2': n_2,'n_3': n_3, 'n_4': n_4, 'n_5': n_5, 'n_6': n_6, 'n_7': n_7,
                             'n_8': n_8, 'n_9': n_9,'n_10': n_10, 'n_11': n_11,'n_12': n_12, 'n_13': n_13, 'n_14': n_14, 'n_15': n_15, 'n_16': n_16,
                             'n_17': n_17, 'n_18': n_18,'n_19': n_19, 'n_20': n_20, 'n_21': n_21, 'n_22': n_22, 'n_23': n_23, 'total': total})

            ## 중복지역
            else:
                for result in results:
                    if result['area_name'] == str_data:
                        result['n_24'] += n_24
                        result['n_1'] += n_1
                        result['n_2'] += n_2
                        result['n_3'] += n_3
                        result['n_4'] += n_4
                        result['n_5'] += n_5
                        result['n_6'] += n_6
                        result['n_7'] += n_7
                        result['n_8'] += n_8
                        result['n_9'] += n_9
                        result['n_10'] += n_10
                        result['n_11'] += n_11
                        result['n_12'] += n_12
                        result['n_13'] += n_13
                        result['n_14'] += n_14
                        result['n_15'] += n_15
                        result['n_16'] += n_16
                        result['n_17'] += n_17
                        result['n_18'] += n_18
                        result['n_19'] += n_19
                        result['n_20'] += n_20
                        result['n_21'] += n_21
                        result['n_22'] += n_22
                        result['n_23'] += n_23
                        result['total'] += total

                        break

    return results


results = []

## 지하철 버스 데이터 추가
results = add_data(subway_data, results)
results = add_data(bus_data, results)

float_population_result = []

for result in results:

    temp = []
    for elements in result.values():
        temp.append(elements)
    float_population_result.append(temp)

columns = ('지역', '24시~1시', '1시~2시', '2시~3시', '3시~4시', '4시~5시', '5시~6시', '6시~7시', '7시~8시', '8시~9시',
           '9시~10시', '10시~11시', '11시~12시', '12시~13시', '13시~14시', '14시~15시', '15시~16시', '16시~17시', '17시~18시',
           '18시~19시', '19시~20시', '20시~21시', '21시~22시', '22시~23시', '23시~24시', '총합')

result_table = pd.DataFrame(float_population_result, columns= columns)
result_table = result_table.sort_values(by=['지역'], ascending=True)
result_table = result_table.reset_index(drop=True)
result_table.to_csv("./float_population_result.csv", encoding="cp949", mode='w', index = True)

In [30]:
result_table

,지역,24시~1시,1시~2시,2시~3시,3시~4시,4시~5시,5시~6시,6시~7시,7시~8시,8시~9시,...,15시~16시,16시~17시,17시~18시,18시~19시,19시~20시,20시~21시,21시~22시,22시~23시,23시~24시,총합
0,서울 강남구 개포동,50340.0,13452.0,0.0,0.0,13031.0,86056.0,194163.0,481632.0,748328.0,...,279557.0,360199.0,495173.0,582190.0,301559.0,218566.0,221117.0,191422.0,112376.0,5971197.0
1,서울 강남구 논현동,103677.0,17901.0,0.0,0.0,72391.0,129490.0,304827.0,734732.0,1303496.0,...,924081.0,1090113.0,1277259.0,1620709.0,1047841.0,726365.0,688389.0,634888.0,302697.0,15660039.0
2,서울 강남구 대치동,117840.0,15474.0,3887.0,4579.0,47307.0,130288.0,265194.0,713927.0,1305475.0,...,954550.0,1032614.0,1211951.0,1397384.0,903385.0,770815.0,646222.0,523110.0,235749.0,15254243.0
3,서울 강남구 도곡동,162711.0,32285.0,10001.0,9844.0,25234.0,157591.0,259652.0,622998.0,1152779.0,...,847004.0,891646.0,1021967.0,1100869.0,585110.0,445378.0,388778.0,324064.0,183766.0,13129074.0
4,서울 강남구 삼성동,64986.0,16137.0,2894.0,2490.0,66028.0,131523.0,305822.0,623929.0,1396543.0,...,595932.0,709068.0,951977.0,1284366.0,717586.0,465719.0,432543.0,353640.0,157544.0,12047470.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176,서울 중랑구 면목동,26523.0,9535.0,4524.0,9568.0,39274.0,140305.0,184802.0,344796.0,518680.0,...,502298.0,493478.0,464061.0,429971.0,311170.0,215327.0,201821.0,154634.0,87747.0,6774765.0
177,서울 중랑구 묵동,4125.0,186.0,0.0,0.0,6941.0,50959.0,42930.0,99672.0,190912.0,...,71852.0,80098.0,89327.0,102397.0,72718.0,47701.0,44902.0,34631.0,20279.0,1421364.0
178,서울 중랑구 상봉동,58008.0,21516.0,6408.0,5847.0,28650.0,119670.0,169361.0,350293.0,553757.0,...,304588.0,327136.0,360126.0,461034.0,311319.0,213381.0,203071.0,187028.0,136955.0,5747827.0
179,서울 중랑구 신내동,24042.0,3895.0,0.0,0.0,109024.0,150673.0,186384.0,334262.0,456893.0,...,352776.0,382389.0,388119.0,396731.0,324313.0,227671.0,200763.0,171732.0,71538.0,5549651.0
180,서울 중랑구 중화동,38327.0,9573.0,1489.0,2888.0,23576.0,106271.0,109577.0,220565.0,405838.0,...,289082.0,320315.0,355799.0,431070.0,319692.0,240131.0,232118.0,223410.0,137355.0,4967398.0

# 구 단위로 묶기

In [22]:
## 구 단위로 묶기
import pandas as pd
import re
subway_data = pd.read_csv('./subway_info_sigudong.csv', encoding= 'CP949', index_col= 0, header= 0, engine= 'python')
bus_data = pd.read_csv('./bus_info_sigudong.csv', encoding= 'CP949', index_col= 0, header= 0, engine= 'python')


areas = []

## 추가 함수
def add_data(csv_data, results):
    for idx,data in enumerate(subway_data['시구동']):
        if pd.isna(data) == False and data !=  '':
            str_data = re.sub('\d+동', '동', data)
            str_list = str_data.split()
            str_data = str_list[0] + ' ' + str_list[1]

            n_24 = csv_data['24시~1시'][idx]
            n_1 = csv_data['1시~2시'][idx]
            n_2 = csv_data['2시~3시'][idx]
            n_3 = csv_data['3시~4시'][idx]
            n_4 = csv_data['4시~5시'][idx]
            n_5 = csv_data['5시~6시'][idx]
            n_6 = csv_data['6시~7시'][idx]
            n_7 = csv_data['7시~8시'][idx]
            n_8 = csv_data['8시~9시'][idx]
            n_9 = csv_data['9시~10시'][idx]
            n_10 = csv_data['10시~11시'][idx]
            n_11 = csv_data['11시~12시'][idx]
            n_12 = csv_data['12시~13시'][idx]
            n_13 = csv_data['13시~14시'][idx]
            n_14 = csv_data['14시~15시'][idx]
            n_15 = csv_data['15시~16시'][idx]
            n_16 = csv_data['16시~17시'][idx]
            n_17 = csv_data['17시~18시'][idx]
            n_18 = csv_data['18시~19시'][idx]
            n_19 = csv_data['19시~20시'][idx]
            n_20 = csv_data['20시~21시'][idx]
            n_21 = csv_data['21시~22시'][idx]
            n_22 = csv_data['22시~23시'][idx]
            n_23 = csv_data['23시~24시'][idx]

            total = n_1 + n_2 + n_3 + n_4 + n_5 + n_6 + n_7 + n_8 + n_9 + n_10 + n_11 + n_12 + n_13 \
                    + n_14 + n_15 + n_16 + n_17 + n_18 + n_19 + n_20 + n_21 + n_22 + n_23 + n_24

            if str_data not in areas:
                areas.append(str_data)
                results.append(
                    {'area_name': str_data, 'n_24': n_24, 'n_1': n_1, 'n_2': n_2,'n_3': n_3, 'n_4': n_4, 'n_5': n_5, 'n_6': n_6, 'n_7': n_7,
                             'n_8': n_8, 'n_9': n_9,'n_10': n_10, 'n_11': n_11,'n_12': n_12, 'n_13': n_13, 'n_14': n_14, 'n_15': n_15, 'n_16': n_16,
                             'n_17': n_17, 'n_18': n_18,'n_19': n_19, 'n_20': n_20, 'n_21': n_21, 'n_22': n_22, 'n_23': n_23, 'total': total})

            ## 중복지역
            else:
                for result in results:
                    if result['area_name'] == str_data:
                        result['n_24'] += n_24
                        result['n_1'] += n_1
                        result['n_2'] += n_2
                        result['n_3'] += n_3
                        result['n_4'] += n_4
                        result['n_5'] += n_5
                        result['n_6'] += n_6
                        result['n_7'] += n_7
                        result['n_8'] += n_8
                        result['n_9'] += n_9
                        result['n_10'] += n_10
                        result['n_11'] += n_11
                        result['n_12'] += n_12
                        result['n_13'] += n_13
                        result['n_14'] += n_14
                        result['n_15'] += n_15
                        result['n_16'] += n_16
                        result['n_17'] += n_17
                        result['n_18'] += n_18
                        result['n_19'] += n_19
                        result['n_20'] += n_20
                        result['n_21'] += n_21
                        result['n_22'] += n_22
                        result['n_23'] += n_23
                        result['total'] += total

                        break

    return results


results = []

## 지하철 버스 데이터 추가
results = add_data(subway_data, results)
results = add_data(bus_data, results)

float_population_result = []

for result in results:

    temp = []
    for elements in result.values():
        temp.append(elements)
    float_population_result.append(temp)

columns = ('지역', '24시~1시', '1시~2시', '2시~3시', '3시~4시', '4시~5시', '5시~6시', '6시~7시', '7시~8시', '8시~9시',
           '9시~10시', '10시~11시', '11시~12시', '12시~13시', '13시~14시', '14시~15시', '15시~16시', '16시~17시', '17시~18시',
           '18시~19시', '19시~20시', '20시~21시', '21시~22시', '22시~23시', '23시~24시', '총합')

result_table = pd.DataFrame(float_population_result, columns= columns)
result_table = result_table.sort_values(by=['지역'], ascending=True)
result_table = result_table.reset_index(drop = True)
result_table.to_csv("./float_population_result_gu.csv", encoding="cp949", mode='w', index = True)

In [23]:
result_table

,지역,24시~1시,1시~2시,2시~3시,3시~4시,4시~5시,5시~6시,6시~7시,7시~8시,8시~9시,...,15시~16시,16시~17시,17시~18시,18시~19시,19시~20시,20시~21시,21시~22시,22시~23시,23시~24시,총합
0,서울 강남구,723349.0,134751.0,35158.0,32281.0,349674.0,830943.0,1834405.0,4491280.0,8142663.0,...,4875944.0,5529496.0,6851714.0,8318040.0,4979055.0,3599100.0,3293032.0,2818659.0,1406709.0,85571806.0
1,서울 강동구,916628.0,318796.0,104467.0,86681.0,376441.0,813370.0,1451651.0,3251019.0,4793374.0,...,3857799.0,4432217.0,4932379.0,5725826.0,4496892.0,3270762.0,3041767.0,2803068.0,1780947.0,65083499.0
2,서울 강북구,487180.0,63620.0,15567.0,15667.0,108585.0,1080520.0,1466823.0,3068976.0,4601958.0,...,3834534.0,4253537.0,4716845.0,5280041.0,3979078.0,2939840.0,2743900.0,2512766.0,1286281.0,61392483.0
3,서울 강서구,1238820.0,334139.0,91016.0,74437.0,1115745.0,2510221.0,3449148.0,6853778.0,10507204.0,...,8749666.0,9648626.0,10369878.0,11327371.0,8680265.0,6280432.0,5517657.0,4927570.0,2820508.0,137640907.0
4,서울 관악구,1037296.0,303563.0,68720.0,47945.0,1346218.0,1636377.0,2122240.0,4826972.0,7303532.0,...,5076425.0,5783895.0,6100854.0,6891297.0,5031870.0,3917431.0,3721148.0,3522496.0,1983129.0,86572310.0
5,서울 광진구,179175.0,51380.0,24679.0,21577.0,103788.0,468822.0,781448.0,1879336.0,2960082.0,...,1929571.0,2153504.0,2494106.0,2965997.0,1927130.0,1528247.0,1433742.0,1195525.0,589746.0,32940462.0
6,서울 구로구,338768.0,58890.0,28899.0,32313.0,308235.0,844756.0,1305124.0,3082942.0,4614040.0,...,2731482.0,3133298.0,3565896.0,4364936.0,3156049.0,2339973.0,2343366.0,2121593.0,1065790.0,50658489.0
7,서울 금천구,35422.0,1901.0,1952.0,2184.0,51603.0,153997.0,284494.0,809392.0,1526643.0,...,531580.0,636542.0,943383.0,1258124.0,774979.0,491120.0,430475.0,369722.0,182109.0,11571932.0
8,서울 노원구,262978.0,58536.0,8258.0,6745.0,277449.0,510082.0,961224.0,2213099.0,2715118.0,...,1923803.0,2189202.0,2360749.0,2736671.0,2209246.0,1559906.0,1431711.0,1322788.0,705189.0,33103233.0
9,서울 도봉구,99528.0,11080.0,609.0,483.0,130605.0,273795.0,412541.0,899441.0,1141382.0,...,857618.0,1035454.0,1023468.0,1115999.0,872486.0,610165.0,565690.0,493544.0,266397.0,14235419.0
10,서울 동대문구,198498.0,41708.0,20367.0,15093.0,39919.0,235251.0,486155.0,1239316.0,2215468.0,...,1700834.0,1957123.0,2050665.0,2277550.0,1601414.0,1250675.0,1231597.0,1016953.0,563709.0,27079630.0
11,서울 동작구,386286.0,123357.0,37921.0,44441.0,715455.0,983757.0,1542164.0,3072445.0,4628210.0,...,2873336.0,3252483.0,3629154.0,4299348.0,2985481.0,2196669.0,1999856.0,1780525.0,933079.0,51751266.0
12,서울 마포구,432148.0,105497.0,46543.0,39473.0,390343.0,972258.0,1262671.0,2706587.0,4791422.0,...,4548811.0,4763429.0,5378009.0,5951042.0,3834207.0,2817455.0,2598071.0,2165345.0,1129437.0,66442829.0
13,서울 서대문구,307085.0,109267.0,40355.0,37787.0,228286.0,476809.0,583356.0,1297677.0,2246450.0,...,1813754.0,1921025.0,2326973.0,2743325.0,1702813.0,1305570.0,1357596.0,1174376.0,637501.0,29499814.0
14,서울 서초구,159258.0,19017.0,4367.0,4675.0,175261.0,383766.0,1001941.0,2160109.0,3637432.0,...,2354024.0,2713617.0,3213828.0,3732648.0,2497217.0,1842517.0,1672245.0,1377212.0,697882.0,40642280.0
15,서울 성동구,445811.0,100077.0,22061.0,24625.0,283059.0,1072891.0,1464080.0,3146284.0,5257208.0,...,3300657.0,3699172.0,4496398.0,5535123.0,3459970.0,2589022.0,2606412.0,2140147.0,1097370.0,57878720.0
16,서울 성북구,768034.0,174130.0,30813.0,17427.0,92893.0,517418.0,1068758.0,2433887.0,3827932.0,...,4086957.0,4678320.0,4998780.0,5607687.0,4064064.0,3097384.0,3157577.0,2863472.0,1630647.0,60831959.0
17,서울 송파구,582409.0,178137.0,55605.0,74663.0,796758.0,1403206.0,2419915.0,5089330.0,7676639.0,...,4709046.0,5249198.0,5666249.0,6370915.0,4511788.0,3287451.0,3021305.0,2509061.0,1288186.0,81806631.0
18,서울 양천구,303019.0,81514.0,36461.0,30648.0,111060.0,424756.0,679424.0,1666289.0,2699027.0,...,1698712.0,1966624.0,2303098.0,2783818.0,1855164.0,1429545.0,1415498.0,1279503.0,741428.0,31110055.0
19,서울 영등포구,347318.0,135265.0,94006.0,94140.0,804438.0,1495909.0,1913900.0,4300919.0,7243322.0,...,3923261.0,4232081.0,5053166.0,5609152.0,3306940.0,2397496.0,2149305.0,1809619.0,961987.0,68871053.0
20,서울 용산구,577928.0,228124.0,72081.0,78877.0,595899.0,1023381.0,1901218.0,4147323.0,6073853.0,...,3838859.0,4392091.0,5028705.0,5976073.0,4595861.0,3332260.0,2998686.0,2582082.0,1413145.0,69652664.0
21,서울 은평구,131548.0,633.0,0.0,0.0,110264.0,390164.0,699431.0,1647489.0,2085973.0,...,1244206.0,1475455.0,1625462.0,1967776.0,1593598.0,1069664.0,957931.0,861786.0,462910.0,23241393.0
22,서울 종로구,361470.0,117441.0,42117.0,49483.0,209524.0,400311.0,646114.0,1574969.0,2763477.0,...,2264044.0,2372956.0,2713776.0,2861693.0,1899305.0,1462545.0,1558272.0,1258211.0,662051.0,34606207.0
23,서울 중구,329130.0,55473.0,10525.0,9201.0,227981.0,627191.0,1137159.0,2973085.0,5191126.0,...,3120359.0,3499546.0,4222731.0,5051448.0,3102704.0,2350320.0,2221978.0,1816174.0,878636.0,53537549.0
24,서울 중랑구,192883.0,55035.0,14241.0,19369.0,224363.0,656840.0,800944.0,1545853.0,2473509.0,...,1874663.0,1971042.0,2067909.0,2273608.0,1693918.0,1218873.0,1143024.0,985673.0,589673.0,29843126.0

In [ ]:
result_